baseURL = 'https://gooseworks.ca/'
languageCode = 'en-CA'
title = 'Gooseworks'

# For lastMod
enableGitInfo = true

# Content and taxonomies
[taxonomies]
  tag = "tags"

# Menu configuration
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Archives"
    url = "/archives/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

# Pagination
paginate = 20
paginatePath = "page"

# Markup configuration
[markup]
  [markup.highlight]
    style = "github"
    lineNos = true

# Front matter configuration
[frontmatter]
  date = ["date", "publishDate"]
  lastMod = ["lastmod", ":git"]
  publishDate = ["publishDate", "date"]

